将Chores/js移至Surge/Scripts，以本地Chores和.github为准覆盖远程项目

diff --git a/.github/workflows/convert.yml b/.github/workflows/convert.yml
--- a/.github/workflows/convert.yml
+++ b/.github/workflows/convert.yml
@@ -53,7 +53,7 @@ jobs:
 
       - name: Extract categories and process plugins
         run: |
-          mkdir -p Chores/sgmodule
+          mkdir -p Surge/Modules
           
           # 从 README.md 提取分类并建立映射关系
           declare -A category_map
@@ -116,21 +116,21 @@ jobs:
             download_url="http://localhost:9101/file/_start_/${plugin_url}/_end_/${encoded_plugin_name}.sgmodule?type=loon-plugin&target=surge-module&target=surge-module&sni=%20%2C%20&del=true&pm=REJECT&category=${encoded_category}&jqEnabled=true"
             
             echo "Processing $plugin_name with category: $category"
-            curl -A "Surge Mac/2985" -L -o "Chores/sgmodule/${plugin_name}.sgmodule" "$download_url" || echo "Failed to download ${plugin_name}.sgmodule"
+            curl -A "Surge Mac/2985" -L -o "Surge/Modules/${plugin_name}.sgmodule" "$download_url" || echo "Failed to download ${plugin_name}.sgmodule"
           done < plugin_urls.txt
 
       - name: Find and replace external JS resources
         continue-on-error: true  # 确保步骤在部分失败时继续执行
         run: |
-          base_js_url="https://github.com/ilychi/esdeath/raw/main/Chores/js"
-          mkdir -p Chores/js
-          for sgmodule_file in Chores/sgmodule/*.sgmodule; do
+          base_js_url="https://github.com/ilychi/esdeath/raw/main/Surge/Scripts"
+          mkdir -p Surge/Scripts
+          for sgmodule_file in Surge/Modules/*.sgmodule; do
             echo "Processing $sgmodule_file"
             # 查找 .js 文件的外部链接
             js_links=$(grep -oP 'https?://[^ ]+\.js' "$sgmodule_file" || echo "")
             for js_link in $js_links; do
               js_filename=$(basename "$js_link")
-              local_js_path="Chores/js/$js_filename"
+              local_js_path="Surge/Scripts/$js_filename"
               # 使用指定的 User-Agent 下载 .js 文件
               echo "Downloading $js_link to $local_js_path"
               if curl -A "Surge Mac/2985" -L -o "$local_js_path" "$js_link"; then
@@ -148,14 +148,14 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          git add Chores/sgmodule/*.sgmodule Chores/js/*.js
+          git add Surge/Modules/*.sgmodule Surge/Scripts/*.js
           if git diff --cached --quiet; then
             echo "No changes to commit"
           else
             git stash
             git pull --rebase  # 同步远程仓库的最新更改以避免冲突
             git stash pop  # 恢复之前的更改
-            git add Chores/sgmodule/*.sgmodule Chores/js/*.js  # 再次添加文件
+            git add Surge/Modules/*.sgmodule Surge/Scripts/*.js  # 再次添加文件
             git commit -m "Update sgmodule files with GitHub-hosted JS resources"
             git push
           fi
